{
    "name": "Partner e-mail validation",
    "version": "18.0.2.0.0",
    "category": "",
    "summary": "Adds e-mail validation to the partner",
    "description": "",
    "author": "Flosslab",
    "website": "https://www.flosslab.com",
    "license": "LGPL-3",
    "sequence": 0,
    "depends": ["base_setup", "contacts", "partner_autocomplete"],
    "external_dependencies": {},
    "data": ["data/ir_config_parameter.xml", "views/res_config_settings.xml"],
    "installable": True,
    "application": False,
    "auto_install": False,
}
